create table trade (

 trade_id varchar(10) generated by default as identity,
 book_id varchar(10),
 counter_party_id varchar(10),
 created_date timestamp, 
 expired boolean, 
 maturity_date timestamp, 
 version varchar(10), 
 primary key (trade_id)
 );

--INSERT INTO TRADE VALUES ('T1', 'B2','CP-3', '2022-08-21','N','2023-05-21', '1'); 
--INSERT INTO TRADE VALUES ('T2', 'B2','CP-3', '2022-08-21','Y','2022-05-21', '1'); 
--INSERT INTO TRADE VALUES ('T3', 'B2','CP-3', '2022-08-21','Y','2022-05-21', '1'); 
--INSERT INTO TRADE VALUES ('T4', 'B2','CP-3', '2022-08-21','N','2023-05-21', '1'); 
--INSERT INTO TRADE VALUES ('T3', 'B2','CP-3', '2022-08-21','N','2023-05-21', '1'); 